export const S = {
  meta: [],
  entries: [],
  stampsByFile: {},
  stFileId: null,
  stDoc: null,
  stBytes: null,
  stPage: 1,
  stPt: {x: 0.15, y: 0.15},
  thumbUrls: new Set(),
  selectionAnchorIndex: -1,
  wsLastSelIdx: -1,
  wsDragFrom: -1,
  wsDragIds: [],
  wsCtrlMouseDown: false,
  wsMsgTimer: 0,
  wsSnackTimer: 0,
  wsImgClickTimer: 0,
  wsLongPressUntil: 0,
  wsEntryMenuOpenId: '',
  wsPreviewToken: 0,
  wsPreviewObjUrl: '',
  stRenderToken: 0,
  stRenderTask: null,
  rsPrevBusy: false,
  rsPrevToken: 0,
  rsPrevTimer: 0,
  mainTab: 'ws',
  wsInternalMode: 'none',
  entryPool: new Map(),
  history: {undo: [], redo: [], max: 50, lock: false}
};

export const C = {
  ocrFile: null,
  srcFile: null,
  ocrWorker: null,
  srcWorker: null,
  ocrAbort: false,
  srcAbort: false,
  ocrText: '',
  srcBytes: null,
  srcName: '',
  libPromises: {},
  fontBuf: null
};
